version: '3.3'
services:
   23cfree:
     image: container-registry.oracle.com/database/free:latest
     volumes:
       - oracle-23c-free:/opt/oracle/oradata
       - ./data:/data
       #- /mnt/disk2/oracle:/disk2
     extra_hosts:
        - "host.docker.internal:host-gateway"
     ports:
       - "8521:1521"
       - "8500:5500"
       #- "8023:8080"
       # - "9043:8443"
     restart: always
     environment:
       ORACLE_PWD: SysPassword1

volumes:
    oracle-23c-free:
